Areas/LOC_Country/Models/LOC_CountryModel.cs
namespace AddEditDemo.Areas.LOC_Country.Models
{
    public class LOC_CountryModel
    {
        public int? CountryID { get; set; }
        public string? CountryName { get; set; }
        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }
        public int StateCount { get; set; }
        public int CityCount { get; set; }
    }
    public class Countrydropdown
    {
        public int? CountryID { get; set; }
        public string? CountryName { get; set; }
    }
}

Areas/EMP_Employee/Controllers/EMP_EmployeeController.cs
using AddEditDemo.DAL;
using AddEditDemo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Practices.EnterpriseLibrary.Data.Sql;
using System;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Drawing;
using System.Net.Sockets;
using System.Net;
using AddEditDemo.Areas.EMP_Employee.Models;
using AddEditDemo.Areas.EMP_Department.Models;
using AddEditDemo.Areas.LOC_Country.Models;

namespace AddEditDemo.Areas.EMP_Employee.Controllers
{

    [Area("Emp_Employee")]
    [Route("Emp_Employee/[Controller]/[action]")]
    public class EMP_EmployeeController : Controller
    {
        EMP_DAL dalEMP = new EMP_DAL();
        MST_DAL dalMST = new MST_DAL();

        #region SelectAll
        public IActionResult SelectAll()
        {
            DataTable dt = dalEMP.dbo_PR_EMP_Employee_SelectAll();
            //string str = this.Configuration.GetConnectionString("myConnectionString");
            ////Prepare a Connection
            //DataTable dt = new DataTable();
            //SqlConnection conn = new SqlConnection(str);
            //conn.Open();
            //SqlCommand objCmd = conn.CreateCommand();
            //objCmd.CommandType = CommandType.StoredProcedure;
            //objCmd.CommandText = "PR_Emp_Employee_SelectAll";
            //SqlDataReader objSDR = objCmd.ExecuteReader();
            //dt.Load(objSDR);

            List<EMP_EmployeeModel> Employee = new List<EMP_EmployeeModel>();
            foreach (DataRow dr in dt.Rows)
            {
                EMP_EmployeeModel EmployeeModel = new EMP_EmployeeModel();
                EmployeeModel.EmployeeID = Convert.ToInt32(dr["EmployeeID"]);
                EmployeeModel.EmployeeName = dr["EmployeeName"].ToString();
                EmployeeModel.Department = dr["Department"].ToString();
                EmployeeModel.Address = dr["Address"].ToString();
                EmployeeModel.Email = dr["Email"].ToString();
                EmployeeModel.Mobile = dr["Mobile"].ToString();
                EmployeeModel.Hobby.Hobby = dr["Hobby"].ToString();
                EmployeeModel.Gender = dr["Gender"].ToString();
                EmployeeModel.Salary = Convert.ToInt32(dr["Salary"]);
                EmployeeModel.JoiningDate = Convert.ToDateTime(dr["JoiningDate"]);
                EmployeeModel.Created = Convert.ToDateTime(dr["Created"]);
                EmployeeModel.Modified = Convert.ToDateTime(dr["Modified"]);
                Employee.Add(EmployeeModel);
            }
            ViewBag.Employee = Employee;

            return View("EMP_EmployeeList",dt);
        }
        #endregion

        #region Delete
        public IActionResult Delete(int EmployeeID)
        {
            DataTable dt = dalEMP.dbo_PR_EMP_Employee_Delete(EmployeeID);

            //return View("EMP_EmployeeList");
            return RedirectToAction("SelectAll");
        }
        #endregion

        #region Add
        public IActionResult Add(int? EmployeeID)
        {
            #region Select For Department Dropdown
            DataTable dt1 = dalEMP.dbo_PR_EMP_Department_SelectByDropdown();
            List<DepartmentDropDown> List = new List<DepartmentDropDown>();
            foreach (DataRow dr1 in dt1.Rows)
            {
                DepartmentDropDown vlst = new DepartmentDropDown();
                vlst.DepID = Convert.ToInt32(dr1["DepID"]);
                vlst.Department = dr1["Department"].ToString();
                List.Add(vlst);
            }
            ViewBag.DepartmentList = List;

            #endregion

            #region HobbyDropdown

            DataTable dt2 = dalEMP.dbo_PR_HOB_Hobby_SelectCheckbox();
            List<HOB_HobbyDropdownModel> List2 = new List<HOB_HobbyDropdownModel>();
            foreach (DataRow dr2 in dt2.Rows)
            {
                HOB_HobbyDropdownModel vlst2 = new HOB_HobbyDropdownModel();
                vlst2.HID = Convert.ToInt32(dr2["HID"]);
                vlst2.Hobby = dr2["Hobby"].ToString();
                List2.Add(vlst2);
            }
            ViewBag.HobbyList = List2;
            #endregion


            if (EmployeeID != null)
            {
                DataTable dt = dalEMP.dbo_PR_EMP_Employee_SelectByPK(EmployeeID);

                EMP_EmployeeModel modelEMP_Employee = new EMP_EmployeeModel();

                foreach (DataRow dr in dt.Rows)
                {
                    modelEMP_Employee.EmployeeID = Convert.ToInt32(dr["EmployeeID"]);
                    modelEMP_Employee.EmployeeName = dr["EmployeeName"].ToString();
                    modelEMP_Employee.DepID = Convert.ToInt32(dr["DepID"]);
                    modelEMP_Employee.Address = dr["Address"].ToString();
                    modelEMP_Employee.Gender = dr["Gender"].ToString();
                    modelEMP_Employee.Mobile = dr["Mobile"].ToString();
                    modelEMP_Employee.Email = dr["Email"].ToString();
                    modelEMP_Employee.JoiningDate = Convert.ToDateTime(dr["JoiningDate"]);
                    modelEMP_Employee.Salary = Convert.ToInt32(dr["Salary"]);

                }
                return View("EMP_EmployeeAddEdit", modelEMP_Employee);
            }
            #region Select For Hobby Checkbox
            //DataTable dt2 = dalEMP.dbo_PR_HOB_Hobby_SelectByDropdown();
            //ViewModels modelHobby = new ViewModels();
            //foreach (DataRow dr2 in dt2.Rows)
            //{
            //    modelHobby.HID = Convert.ToInt32(dr2["HID"]);
            //    modelHobby.Hobby = dr2["Hobby"].ToString();
            //}
            //return View("EMP_EmployeeAddEdit", modelHobby);

            ////List<HobbyDropdown> List1 = new List<HobbyDropdown>();
            ////foreach (DataRow dr2 in dt2.Rows)
            ////{
            ////    HobbyDropdown vlst1 = new HobbyDropdown();
            ////    vlst1.HID = Convert.ToInt32(dr2["HID"]);
            ////    vlst1.Hobby = dr2["Hobby"].ToString();
            ////    List1.Add(vlst1);
            ////}
            ////ViewBag.HobbyList = List1;

            #endregion

            return View("EMP_EmployeeAddEdit");
        }
        #endregion

        #region Save
        [HttpPost]
        public IActionResult Save(EMP_EmployeeModel modelEMP_Employee)
        {
            //if (modelEMP_Employee.EmployeeID == null)
            //{
            #region Photo Upload Starts here
            if (modelEMP_Employee.File != null)
            {
                string FilePath = "wwwroot\\Upload";
                string path = Path.Combine(Directory.GetCurrentDirectory(), FilePath);
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                string fileNameWithPath = Path.Combine(path, modelEMP_Employee.File.FileName);
                modelEMP_Employee.PhotoPath = FilePath.Replace("wwwroot\\", "/") + "/" + modelEMP_Employee.File.FileName;
                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                {
                    modelEMP_Employee.File.CopyTo(stream);
                }
            }
            #endregion

            #region Insert
            //DataTable dt = dalEMP.dbo_PR_EMP_Employee_Insert(modelEMP_Employee);
            if (modelEMP_Employee.EmployeeID == null)
            {
                if (Convert.ToBoolean(dalEMP.dbo_PR_EMP_Employee_Insert(modelEMP_Employee)))
                    if (Convert.ToBoolean(dalEMP.dbo_PR_EWH_EmployeeWiseHobby_Insert(modelEMP_Employee)))
                        TempData["EmployeeInsertMsg"] = "Record Inserted Successfully";
                return RedirectToAction("Add");

            }
            #endregion

             #region Update
            else
            {
                if (Convert.ToBoolean(dalEMP.dbo_PR_EMP_Employee_Update(modelEMP_Employee)))
                    if (Convert.ToBoolean(dalEMP.dbo_PR_EWH_EmployeeWiseHobby_Insert(modelEMP_Employee)))
                        TempData["EmployeeInsertMsg"] = "Record Updated Successfully";

                return RedirectToAction("Add");


            }
            //TempData["EmployeeInsertMsg"] = "Record Inserted Successfully ! ";
            #endregion

            //}
            //else
            //{
            //    #region Update
            //    DataTable dt = dalEMP.dbo_PR_EMP_Employee_Update(modelEMP_Employee);

            //    TempData["EmployeeInsertMsg"] = "Record Updated Successfully ! ";
            //    #endregion
            //}

            return RedirectToAction("Add");
            //return View("EMP_EmployeeAddEdit");
        }
        #endregion

        #region filter 
        public IActionResult Filter(string EmployeeName, string Gender, string Email)
        {
            DataTable dt = dalEMP.dbo_PR_EMP_Employee_SelectByPage(EmployeeName, Gender, Email);

            //List<EMP_EmployeeModel> Employee = new List<EMP_EmployeeModel>();
            //foreach (DataRow dr in dt.Rows)
            //{
            //    EMP_EmployeeModel EmployeeModel = new EMP_EmployeeModel();
            //    EmployeeModel.EmployeeID = Convert.ToInt32(dr["EmployeeID"]);
            //    EmployeeModel.EmployeeName = dr["EmployeeName"].ToString();
            //    EmployeeModel.Department = dr["Department"].ToString();
            //    EmployeeModel.Address = dr["Address"].ToString();
            //    EmployeeModel.Email = dr["Email"].ToString();
            //    EmployeeModel.Mobile = dr["Mobile"].ToString();
            //    EmployeeModel.Hobby.Hobby = dr["Hobby"].ToString();
            //    EmployeeModel.Gender = dr["Gender"].ToString();
            //    EmployeeModel.Salary = Convert.ToInt32(dr["Salary"]);
            //    EmployeeModel.JoiningDate = Convert.ToDateTime(dr["JoiningDate"]);
            //    EmployeeModel.Created = Convert.ToDateTime(dr["Created"]);
            //    EmployeeModel.Modified = Convert.ToDateTime(dr["Modified"]);

Areas/LOC_Country/Controllers/LOC_CountryController.cs
using AddEditDemo.Areas.LOC_Country.Models;
using AddEditDemo.DAL;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Diagnostics.Metrics;

namespace AddEditDemo.Areas.LOC_Country.Controllers
{
    [Area("LOC_Country")]
    [Route("[Controller]/[action]")]
    public class LOC_CountryController : Controller
    {
        LOC_DAL dalLOC = new LOC_DAL();

        #region SelectAll
        public IActionResult SelectAll()
        {
            DataTable dt = dalLOC.dbo_PR_LOC_Country_SelectAll();
            List<LOC_CountryModel> Country = new List<LOC_CountryModel>();
            foreach (DataRow dr in dt.Rows)
            {
                LOC_CountryModel CountryModel = new LOC_CountryModel();
                CountryModel.CountryID = Convert.ToInt32(dr["CountryID"]);
                CountryModel.CountryName = dr["CountryName"].ToString();
                CountryModel.StateCount = Convert.ToInt32(dr["StateCount"]);
                CountryModel.CityCount = Convert.ToInt32(dr["CityCount"]);
                CountryModel.Created = Convert.ToDateTime(dr["Created"]);
                CountryModel.Modified = Convert.ToDateTime(dr["Modified"]);
                Country.Add(CountryModel);
            }
            ViewBag.Country = Country;
            return View("LOC_CountryList");
        }
        #endregion

        #region Delete
        public IActionResult Delete(int CountryID)
        {
            DataTable dt = dalLOC.dbo_PR_LOC_Country_Delete(CountryID);

            //return View("EMP_EmployeeList");
            return RedirectToAction("SelectAll");
        }
        #endregion

        #region Add
        public IActionResult Add(int? CountryID)
        {
            if (CountryID != null)
            {
                DataTable dt = dalLOC.dbo_PR_LOC_Country_SelectByPK(CountryID);

                LOC_CountryModel modelLOC_Country = new LOC_CountryModel();

                foreach (DataRow dr in dt.Rows)
                {
                    modelLOC_Country.CountryID = Convert.ToInt32(dr["CountryID"]);
                    modelLOC_Country.CountryName = dr["CountryName"].ToString();

                }
                return View("LOC_CountryAddEdit", modelLOC_Country);
            }

            return View("LOC_CountryAddEdit");
        }
        #endregion

        #region Save
        [HttpPost]
        public IActionResult Save(LOC_CountryModel modelLOC_Country)
        {
            if (modelLOC_Country.CountryID == null)
            {
                #region Insert
                DataTable dt = dalLOC.dbo_PR_LOC_Country_Insert(modelLOC_Country);

                TempData["CountryInsertMsg"] = "Record Inserted Successfully ! ";
                #endregion
            }
            else
            {
                #region Update
                DataTable dt = dalLOC.dbo_PR_LOC_Country_Update(modelLOC_Country);

                TempData["CountryInsertMsg"] = "Record Updated Successfully ! ";
                #endregion
            }

            return RedirectToAction("ADD");
            //return View("LOC_CountryAddEdit");
        }
        #endregion

        #region filter 
        public IActionResult Filter(string CountryName)
        {
            DataTable dt = dalLOC.dbo_PR_LOC_Country_SelectByCountryName(CountryName);
            List<LOC_CountryModel> Country = new List<LOC_CountryModel>();
            foreach (DataRow dr in dt.Rows)
            {
                LOC_CountryModel CountryModel = new LOC_CountryModel();
                CountryModel.CountryID = Convert.ToInt32(dr["CountryID"]);
                CountryModel.CountryName = dr["CountryName"].ToString();
                CountryModel.StateCount = Convert.ToInt32(dr["StateCount"]);
                CountryModel.CityCount = Convert.ToInt32(dr["CityCount"]);
                CountryModel.Created = Convert.ToDateTime(dr["Created"]);
                CountryModel.Modified = Convert.ToDateTime(dr["Modified"]);
                Country.Add(CountryModel);
            }
            ViewBag.Country = Country;
            return View("LOC_CountryList");
        }
        #endregion
    }
}

Areas/LOC_Country/Views/LOC_Country/LOC_CountryAddEdit.cshtml
@{
    ViewData["Title"] = "LOC_CountryAddEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Data;

@model AddEditDemo.Areas.LOC_Country.Models.LOC_CountryModel
<div class="pagetitle">
    <div><h1>Country Add Edit</h1></div>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="EMP_Employee" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item"><a asp-controller="LOC_Country" asp-action="SelectAll">Country</a></li>
            <li class="breadcrumb-item">Country Add Edit</li>

        </ol>
    </nav>

</div><!-- End Page Title -->

<div class="container">
    <div class="fs-2">
    </div>
</div>
<div class="row">
    <div class="col-lg-12">

        <div class="card">
            <div class="card-body">
                <h3> LOC_Country AddEdit</h3>

                <div asp-validation-summary="ModelOnly"></div>

                <div class="container-fluid">
                    <h3>@TempData["CountryInsertMsg"]</h3>
                    <form method="post" asp-controller="LOC_Country" asp-action="Save">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        @Html.HiddenFor(x=>x.CountryID)

                        <div class="row-mb-3">
                            <div class="fw-bold"><label class="col-sm-2 col-form-label" asp-for="CountryName"><span class="text-danger fw-bold">*</span>Country Name</label></div>
                            <div class="col-sm-12"><input type="text" class="form-control" asp-for="CountryName" autocomplete="off" /></div>
                            <span class="text-danger" asp-validation-for="CountryName"></span>
                        </div>

                      
                       


                        <br /><hr />
                        <div class="text-left">
                            <button type="submit" class="btn btn-success" value="Submit">Submit</button>
                            <a class="btn btn-secondary" asp-controller="LOC_Country" asp-action="SelectAll">Back to List</a>
                        </div>
                    </form>
                </div>

            </div>
        </div>

    </div>


</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Areas/LOC_Country/Views/LOC_Country/LOC_CountryList.cshtml
@{
    ViewData["Title"] = "LOC_CountryList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using AddEditDemo.Areas.LOC_Country.Models;
@model AddEditDemo.Areas.LOC_Country.Models.LOC_CountryModel
<div class="pagetitle">
    <div><h1>Country List</h1></div>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item">Country List</li>
        </ol>
    </nav>

</div><!-- End Page Title -->

<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card responsive">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-11"><h3>Country List</h3></div>
                        <div class="col-md-1"><form method="post" asp-controller="LOC_Country" asp-action="Add"><button type="submit" class="btn btn-success">Add</button></form></div>
                    </div>
                    <br />
                    <partial name="_FilterCountry" />
                    <hr />
                    <!-- Table with stripped rows -->
                    <table class="table datatable text-center">
                        <thead >
                            <tr>
                                <th scope="col">CountryID</th>
                                <th scope="col">Country Name</th>
                                <th scope="col">State Count</th>
                                <th scope="col">City Count</th>
                                <th scope="col">Created</th>
                                <th scope="col">Modified</th>
                                <th scope="col" style="text-align: center;">Action</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            @foreach (LOC_CountryModel dr in ViewBag.Country)
                            {
                                <tr >
                                    <td scope="row">@dr.CountryID</td>
                                    <td scope="col">@dr.CountryName</td>
                                    <td scope="col"><a asp-controller="LOC_State" asp-action="SelectAll" asp-route-CountryID="@(Convert.ToInt32(dr.CountryID))">@dr.StateCount</a></td>
                                    <td scope="col"><a asp-controller="LOC_City" asp-action="SelectAll" asp-route-CountryID="@(Convert.ToInt32(dr.CountryID))">@dr.CityCount</a></td>
                                    <td scope="col">@Convert.ToDateTime(@dr.Created).ToString("dd-MM-yyyy")</td>
                                    <td scope="col">@Convert.ToDateTime(@dr.Modified).ToString("dd-MM-yyyy")</td>
                                    <td scope="col">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <form method="post" asp-controller="LOC_Country" asp-action="Add" asp-route-Countryid="@(Convert.ToInt32(dr.CountryID))">
                                                    <input type="hidden" name="CountryID" value="@Convert.ToInt32(dr.CountryID)" />
                                                    <button type="submit" class="btn btn-secondary ">

                                                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="25" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                                            <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                                                        </svg>
                                                    </button>
                                                </form>
                                            </div>
                                            <div class="col-md-6">
                                                <form method="post" asp-controller="LOC_Country" asp-action="Delete">
                                                    <input type="hidden" name="CountryID" value="@Convert.ToInt32(dr.CountryID)" />
                                                    <button onclick="return fun1()" type="submit" class="btn btn-danger">

                                                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="25" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z" />
                                                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z" />
                                                        </svg>
                                                    </button>
                                                </form>
                                            </div>
                                        </div>
                                    </td>

                                </tr>
                            }

                        </tbody>
                    </table>
                    <!-- End Table with stripped rows -->

                </div>
            </div>

        </div>
    </div>
</section>

@section Scripts{
    <script>
        function fun1() {
            if (confirm("Are You Sure You Want To Delete")) {
                return true;
            }
            else {
                return false;
            }
        }
    </script>
    <script src="~/js/datatablejs.js"></script>
}